apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: follow-jeroenvisser-online-ingress
  namespace: ${KUBE_APP_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
    - hosts:
      - ${DOMAIN_NAME}
      secretName: letsencrypt-production
  rules:
    - host: ${DOMAIN_NAME}
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: ${KUBE_APP_NAMESPACE}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: Service
apiVersion: v1
metadata:
  name: wordpress
  namespace: ${KUBE_APP_NAMESPACE}
  labels:
    run: wordpress
spec:
  selector:
    run: wordpress
  ports:
    - port: 80
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: wordpress
  namespace: ${KUBE_APP_NAMESPACE}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
        - name: wordpress
          image: jvisser/follow.jeroenvisser.online-website:731a1f2
          ports:
              - containerPort: 80
          envFrom:
            - secretRef:
                name: app-config
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim